controllers/SettingController.php
<?php

namespace app\controllers;

use app\components\CController;
use app\models\Setting;
use app\models\SettingSearch;
use yii\web\HttpException;
use yii\helpers\Url;

/**
 * SettingController implements the CRUD actions for Setting model.
 */
class SettingController extends CController
{
    /**
     * Lists all Setting models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SettingSearch;
        $dataProvider = $searchModel->search($_GET);

        Url::remember();
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel'  => $searchModel,
        ]);
    }

    /**
     * Displays a single Setting model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($setting_id)
    {
        Url::remember();
        return $this->render('view', [
            'model' => $this->findModel($setting_id),
        ]);
    }

    /**
     * Creates a new Setting model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Setting;

        try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect(['view', 'setting_id' => $model->setting_id]);
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model,]);
    }

    /**
     * Updates an existing Setting model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($setting_id)
    {
        $model = $this->findModel($setting_id);

        if ($model->load($_POST) && $model->save()) {
            return $this->redirect(['view', 'setting_id' => $model->setting_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Setting model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($setting_id)
    {
        $this->findModel($setting_id)->delete();
        return $this->redirect(Url::previous());
    }

    /**
     * Finds the Setting model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Setting the loaded model
     * @throws HttpException if the model cannot be found
     */
    protected function findModel($setting_id)
    {
        if (($model = Setting::findOne($setting_id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
}

controllers/TaskController.php
<?php

namespace app\controllers;

use app\components\CController;
use app\models\NotificationEmailSearch;
use app\models\ParseResultSearch;
use app\models\Task;
use app\models\TaskCategorySearch;
use app\models\TaskHasNotificationEmail;
use app\models\TaskSearch;
use dosamigos\grid\ToggleAction;
use yii\web\HttpException;
use yii\helpers\Url;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends CController
{
    public function actions()
    {
        return [
            'toggle' => [
                'class'      => ToggleAction::className(),
                'modelClass' => Task::className(),
                'onValue'    => 1,
                'offValue'   => 0
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TaskSearch;
        $dataProvider = $searchModel->search($_GET);

        Url::remember();
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel'  => $searchModel,
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($task_id)
    {
        $searchModel = new NotificationEmailSearch();
        $dataProvider = $searchModel->searchByTask($_GET, $task_id);

        $searchModel = new TaskCategorySearch;
        $dataProviderCategory = $searchModel->searchByTask($_GET, $task_id);

        $searchModelResult = new ParseResultSearch;
        $dataProviderResult = $searchModelResult->searchByTask($_GET, $task_id);
        Url::remember();
        return $this->render('view', [
            'model'                => $this->findModel($task_id),
            'dataProviderEmail'    => $dataProvider,
            'dataProviderCategory' => $dataProviderCategory,
            'dataProviderResult'   => $dataProviderResult,
            'searchModelResult'    => $searchModelResult
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Task;

        try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect(['/task/view', 'task_id' => $model->primaryKey]);
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model,]);
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($task_id)
    {
        $model = $this->findModel($task_id);

        if ($model->load($_POST) && $model->save()) {
            return $this->redirect(['/task/view', 'task_id' => $model->primaryKey]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param      $task_id
     * @param null $notification_email_id
     * @return mixed
     * @throws HttpException
     * @throws \Exception
     * @internal param int $id
     */
    public function actionDelete($task_id, $notification_email_id = null)
    {
        if ($notification_email_id) {
            if (
                (
                $model = TaskHasNotificationEmail::find()
                    ->where(
                        [
                            'task_has_notification_email_task_id'               => $task_id,
                            'task_has_notification_email_notification_email_id' => $notification_email_id]
                    )->one()) !== null
            ) {
            } else {
                throw new HttpException(404, 'The requested page does not exist.');
            }
            $model->delete();
        } else {
            $this->findModel($task_id)->delete();
        }

        return $this->redirect(Url::previous());
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws HttpException if the model cannot be found
     */
    protected function findModel($task_id)
    {
        if (($model = Task::findOne($task_id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\components\CController;
use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends CController
{
    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel'  => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();
        $model->setScenario('register');
        $model->status = User::STATUS_ACTIVE;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/content.php
<?php
use app\components\widgets\Alert;
use yii\widgets\Breadcrumbs;

?>
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            <?php
            if ($this->title !== null) {
                echo $this->title;
            } else {
                echo \yii\helpers\Inflector::camel2words(\yii\helpers\Inflector::id2camel($this->context->module->id));
                echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
            } ?>
        </h1>
        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

views/layouts/left.php
<?php

use yii\bootstrap\Nav;

/** @var \app\models\User $user */

?>
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= ucfirst($user->username); ?></p>

                <?=
                \yii\helpers\Html::a(
                    '<i class="fa fa-circle text-success"></i> Online</a>',
                    ['/user/view', 'id' => $user->id]
                ); ?>
            </div>
        </div>

        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <?=
        Nav::widget(
            [
                'encodeLabels' => false,
                'options'      => ['class' => 'sidebar-menu'],
                'items'        => [
                    '<li class="header">Menu Yii2</li>',
                    ['label' => '<i class="fa fa-file-code-o"></i><span>Gii</span>', 'url' => ['/gii']],
                    ['label' => '<i class="fa fa-dashboard"></i><span>Debug</span>', 'url' => ['/debug']],
                    ['label' => '', 'url' => ['#'], 'options' => ['class' => 'divider']],
                    [
                        'label' => '<span>Пользователи</span>',
                        'active' => Yii::$app->controller->id === 'user',
                        'items'        => [
                            '<li class="header">Управление пользователями</li>',
                            ['label' => '<span>Список пользователей</span>', 'url' => ['/user']],
                            ['label' => '<span>Создать пользователя</span>', 'url' => ['/user/create']],
                        ],
                    ],
                    [
                        'label' => '<span>Задачи</span>',
                        'active' => Yii::$app->controller->id === 'task'
                            || Yii::$app->controller->id === 'parse-result'
                            || Yii::$app->controller->id === 'task-category',
                        'items'        => [
                            '<li class="header">Управление задачами</li>',
                            ['label' => '<span>Список задач</span>', 'url' => ['/task']],
                            ['label' => '<span>Создать задачу</span>', 'url' => ['/task/create']],
                            ['label' => '', 'url' => ['#'], 'options' => ['class' => 'divider']],
                            ['label' => '<span>Список категорий</span>', 'url' => ['/task-category']],
                            ['label' => '', 'url' => ['#'], 'options' => ['class' => 'divider']],
                            ['label' => '<span>Список результатов</span>', 'url' => ['/parse-result']],
                        ],
                    ],
                    [
                        'label' => '<span>E-mail</span>',
                        'active' => Yii::$app->controller->id === 'notification-email',
                        'items'        => [
                            '<li class="header">Управление E-mail</li>',
                            ['label' => '<span>Список e-mail</span>', 'url' => ['/notification-email']],
                            ['label' => '<span>Создать e-mail</span>', 'url' => ['/notification-email/create']],
                        ],
                    ],
                    ['label' => '', 'url' => ['#'], 'options' => ['class' => 'divider']],
                    [
                        'label' => '<span>Настройки</span>',
                        'active' => Yii::$app->controller->id === 'setting',
                        'items'        => [
                            '<li class="header">Управление настройками</li>',
                            ['label' => '<span>Список настроек</span>', 'url' => ['/setting']],
                            ['label' => '<span>Создать настройку</span>', 'url' => ['/setting/create']],
                        ],
                    ],
                    ['label' => '', 'url' => ['#'], 'options' => ['class' => 'divider']],
                    [
                        'label'   => '<i class="glyphicon glyphicon-lock"></i><span>Вход</span>', //for basic
                        'url'     => ['/site/login'],
                        'visible' => Yii::$app->user->isGuest
                    ],
                    ['label' => '', 'url' => ['#'], 'options' => ['class' => 'divider']],
                    [
                        'label'   => '<i class="glyphicon glyphicon-lock"></i><span>Выход</span>', //for basic
                        'url'     => ['/site/logout'],
                        'visible' => !Yii::$app->user->isGuest
                    ],
                ],
            ]
        );
        ?>

    </section>

</aside>

views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

app\assets\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="login-page">

    <?php $this->beginBody() ?>

    <?= $content ?>

    <?php $this->endBody() ?>
    </body>
    </html>
<?php $this->endPage();

views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
if (Yii::$app->controller->action->id === 'login') {
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    app\assets\AppAsset::register($this);
    app\assets\AdminLteAsset::register($this);

    $user = \app\models\User::findOne(Yii::$app->user->id);
    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/bower/admin-lte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?=
        $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset, 'user' => $user]
        ) ?>

        <?=
        $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset, 'user' => $user]
        )
        ?>

        <?=
        $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php
}